name: Documentation Change
description: Request an addition or correction to the documentation.
labels: ["Documentation"]
body:
  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: Describe what you'd like added, corrected, or clarified.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm all of the following before submitting.
      options:
        - label: I am willing to cooperate to provide more details if needed.
          required: true
        - label: I understand that I must speak in the English language to make communication easier.
          required: true
